name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*.*.*"   # 例如 v1.0.0 时触发

jobs:
  docker:
    runs-on: ubuntu-latest   # 默认就是 amd64 runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64   # 只构建 amd64，不走 QEMU
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mock-data:${{ github.ref_name }}